# Sheet I/O for the AFUVAI Vendor Price Monitor (D2 hybrid model):
# - read/write the canonical CSVs in data/
# - generate the full "AFUVAI Vendor Price Monitor.xlsx" workbook for Drive
# - parse rows back out of a downloaded workbook (Quick Entry / Proposals)
# - merge parsed rows into price-log.csv with dedupe on
#   (vendor_id, stem_id, date, price_per_stem)

from __future__ import annotations

import csv
from datetime import date, datetime
from pathlib import Path

from openpyxl import Workbook, load_workbook
from openpyxl.styles import Alignment, Font, PatternFill
from openpyxl.utils import get_column_letter

from pricemonitor.models import (
    CONFIG_DIR,
    DATA_DIR,
    PRICE_LOG_COLUMNS,
    PROPOSAL_COLUMNS,
    PriceLogRow,
    ProposalRow,
    load_seasonal_calendar,
    load_stems,
    load_thresholds,
    load_tier_recipes,
    load_vendors,
    normalize_price_per_stem,
)

WORKBOOK_NAME = "AFUVAI Vendor Price Monitor.xlsx"

TAB_READ_ME = "Read Me"
TAB_QUICK_ENTRY = "Quick Entry"
TAB_PRICE_LOG = "Price Log"
TAB_PROPOSALS = "Proposals"
TAB_VENDORS = "Vendors"
TAB_SUBSTITUTIONS = "Substitutions & Units"
TAB_TIER_RECIPES = "Tier Recipes"
TAB_SEASONAL = "Seasonal Calendar"
TAB_COMPARISON = "Comparison"
TAB_DIGEST = "Digest Archive"

# Fields a human types in Quick Entry. id / price_per_stem / entered_at / status
# are computed at merge time so hand entry stays simple.
QUICK_ENTRY_COLUMNS = [
    "date", "vendor_id", "stem_id", "variety", "grade", "quoted_price",
    "quote_unit", "units_per_quote_unit", "currency", "source", "baseline",
    "valid_until", "disruption_tag", "notes", "entered_by",
]

HEADER_FILL = PatternFill("solid", fgColor="1F3A5F")
HEADER_FONT = Font(bold=True, color="FFFFFF")
NOTE_FILL = PatternFill("solid", fgColor="FFF3CD")
NOTE_FONT = Font(italic=True, color="7A5C00")
READONLY_FILL = PatternFill("solid", fgColor="E8E8E8")

READ_ME_LINES = [
    ("AFUVAI Vendor Price Monitor", True),
    ("", False),
    ("What this is", True),
    ("Tracks wholesale flower quotes across AFUVAI's 10 vendors, normalized to per-stem prices,", False),
    ("and feeds the 6-tier bulk margin model (60% target). The canonical history lives in the", False),
    ("repo's data/price-log.csv (git); this workbook is the hands-on entry and review surface.", False),
    ("", False),
    ("How to use it — the only two tabs you edit", True),
    ("1. 'Quick Entry' — paste a quote you got by phone/email: one row per (vendor, stem, date).", False),
    ("   Leave units_per_quote_unit blank on bunch quotes to use the stem's default bunch count.", False),
    ("   The weekly run picks these rows up, computes per-stem price, and merges them into the log.", False),
    ("2. 'Proposals' — quotes the email agent extracted from Gmail. Change the status column to", False),
    ("   'confirmed' to accept a row into the price log, or 'rejected' to discard it. Nothing", False),
    ("   enters the log until you confirm it.", False),
    ("", False),
    ("Everything else is generated", True),
    ("'Price Log', 'Vendors', 'Substitutions & Units', 'Tier Recipes', 'Seasonal Calendar',", False),
    ("'Comparison' and 'Digest Archive' are regenerated by the weekly job from the repo config", False),
    ("and CSVs. Edits there will be overwritten — change config in the repo instead.", False),
    ("", False),
    ("Ground rules (same spirit as the Expense Tracker's Read Me)", True),
    ("- Do not add/rename/reorder columns or tabs; the automation parses them by position.", False),
    ("- Dates are YYYY-MM-DD. quote_unit is one of: stem, bunch, box.", False),
    ("- grade is premium / standard / economy — never compare prices across grades.", False),
    ("- Rows with status 'sample' are illustrative seed data; filter them out of any analysis.", False),
    ("- Quotes older than 60 days are flagged aging; older than 90 days are stale and excluded", False),
    ("  from current comparisons.", False),
]


# --- CSV I/O -------------------------------------------------------------------

def read_price_log(csv_path: Path = DATA_DIR / "price-log.csv") -> list[PriceLogRow]:
    with open(csv_path, newline="", encoding="utf-8") as handle:
        return [PriceLogRow.from_csv_row(row) for row in csv.DictReader(handle)]


def write_price_log(rows: list[PriceLogRow], csv_path: Path = DATA_DIR / "price-log.csv") -> None:
    with open(csv_path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=PRICE_LOG_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow(row.to_csv_row())


def read_proposals(csv_path: Path = DATA_DIR / "proposals.csv") -> list[ProposalRow]:
    with open(csv_path, newline="", encoding="utf-8") as handle:
        return [ProposalRow.from_csv_row(row) for row in csv.DictReader(handle)]


def write_proposals(rows: list[ProposalRow], csv_path: Path = DATA_DIR / "proposals.csv") -> None:
    with open(csv_path, "w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=PROPOSAL_COLUMNS)
        writer.writeheader()
        for row in rows:
            writer.writerow(row.to_csv_row())


# --- Workbook generation -------------------------------------------------------

def _style_header(sheet, row_index: int, column_count: int) -> None:
    for column in range(1, column_count + 1):
        cell = sheet.cell(row=row_index, column=column)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT


def _add_note_row(sheet, text: str, column_count: int) -> None:
    sheet.cell(row=1, column=1, value=text)
    sheet.merge_cells(start_row=1, start_column=1, end_row=1, end_column=max(column_count, 1))
    cell = sheet.cell(row=1, column=1)
    cell.fill = NOTE_FILL
    cell.font = NOTE_FONT
    cell.alignment = Alignment(wrap_text=False)


def _autosize(sheet, widths: dict[int, int] | None = None, default: int = 16) -> None:
    for column in range(1, (sheet.max_column or 1) + 1):
        sheet.column_dimensions[get_column_letter(column)].width = (widths or {}).get(column, default)


def _write_table(sheet, headers: list[str], rows: list[list], note: str | None = None) -> None:
    header_row = 1
    if note:
        _add_note_row(sheet, note, len(headers))
        header_row = 2
    for column, header in enumerate(headers, start=1):
        sheet.cell(row=header_row, column=column, value=header)
    _style_header(sheet, header_row, len(headers))
    for offset, row in enumerate(rows, start=header_row + 1):
        for column, value in enumerate(row, start=1):
            sheet.cell(row=offset, column=column, value=value)
    sheet.freeze_panes = sheet.cell(row=header_row + 1, column=1)
    _autosize(sheet)


def build_workbook(
    output_path: Path | None = None,
    config_dir: Path = CONFIG_DIR,
    data_dir: Path = DATA_DIR,
) -> Path:
    output_path = output_path or (CONFIG_DIR.parent / WORKBOOK_NAME)
    vendors = load_vendors(config_dir)
    stems = load_stems(config_dir)
    recipes = load_tier_recipes(config_dir)
    calendar = load_seasonal_calendar(config_dir)
    thresholds = load_thresholds(config_dir)

    workbook = Workbook()

    # Read Me
    sheet = workbook.active
    sheet.title = TAB_READ_ME
    for index, (line, bold) in enumerate(READ_ME_LINES, start=1):
        cell = sheet.cell(row=index, column=1, value=line)
        if bold:
            cell.font = Font(bold=True, size=12)
    sheet.column_dimensions["A"].width = 100

    # Quick Entry (editable)
    sheet = workbook.create_sheet(TAB_QUICK_ENTRY)
    _write_table(
        sheet, QUICK_ENTRY_COLUMNS, [],
        note=("EDITABLE — one quote per row. date=YYYY-MM-DD, quote_unit=stem|bunch|box, "
              "leave units_per_quote_unit blank to use the stem's default bunch count, "
              "source=email|phone|manual|portal, baseline=true for a vendor's first quote."),
    )

    # Price Log (generated mirror of data/price-log.csv)
    sheet = workbook.create_sheet(TAB_PRICE_LOG)
    log_rows = read_price_log(data_dir / "price-log.csv")
    _write_table(
        sheet, PRICE_LOG_COLUMNS,
        [[row.to_csv_row()[column] for column in PRICE_LOG_COLUMNS] for row in log_rows],
        note="GENERATED — read-only mirror of data/price-log.csv. Add quotes in Quick Entry instead.",
    )

    # Proposals (status column is the human confirm/reject switch)
    sheet = workbook.create_sheet(TAB_PROPOSALS)
    proposal_rows = read_proposals(data_dir / "proposals.csv")
    _write_table(
        sheet, PROPOSAL_COLUMNS,
        [[row.to_csv_row()[column] for column in PROPOSAL_COLUMNS] for row in proposal_rows],
        note=("REVIEW — quotes extracted from Gmail by the ingestion agent. Edit ONLY the 'status' "
              "column: set to confirmed (accept into price log) or rejected. Optionally add review_note."),
    )

    # Vendors
    sheet = workbook.create_sheet(TAB_VENDORS)
    vendor_headers = [
        "id", "name", "branch", "company_group", "email", "phone", "website", "address",
        "rep_name", "rep_notes", "payment_terms", "min_order_usd", "standing_order_requirement",
        "delivery_days", "delivery_window", "delivery_method", "lead_time_days",
        "valentines_cutoff", "mothers_day_cutoff", "has_public_pricing", "public_price_url",
        "email_domains", "active", "notes",
    ]
    vendor_rows = []
    for vendor in vendors["vendors"]:
        contact, rep = vendor["contact"], vendor["rep"]
        delivery, cutoffs, page = vendor["delivery"], vendor["holiday_cutoffs"], vendor["public_price_page"]
        vendor_rows.append([
            vendor["id"], vendor["name"], vendor["branch"], vendor["company_group"],
            contact["email"], contact["phone"], contact["website"], contact["address"],
            rep["name"], rep["notes"], vendor["payment_terms"], vendor["min_order_usd"],
            vendor["standing_order_requirement"], delivery["days"], delivery["window"],
            delivery["method"], vendor["lead_time_days"], cutoffs["valentines"],
            cutoffs["mothers_day"], page["has_public_pricing"], page["url"],
            ", ".join(vendor["email_domains"]), vendor["active"], vendor["notes"],
        ])
    _write_table(
        sheet, vendor_headers, vendor_rows,
        note="GENERATED from config/vendors.json — blanks are pending WS1 research. Edit the JSON, not this tab.",
    )

    # Substitutions & Units
    sheet = workbook.create_sheet(TAB_SUBSTITUTIONS)
    stem_headers = [
        "stem_id", "display_name", "market_price", "grades", "bunch_default_count",
        "box_default_count", "substitutes", "notes",
    ]
    stem_rows = []
    for stem in stems["stems"]:
        substitutes = "; ".join(
            f"{item['stem_id']} ({item['note']})" if item.get("note") else item["stem_id"]
            for item in stem["substitutes"]
        )
        stem_rows.append([
            stem["id"], stem["display_name"], stem["market_price"],
            ", ".join(stem["default_grade_levels"]), stem["units"]["bunch_default_count"],
            stem["units"]["box_default_count"], substitutes, stem.get("notes"),
        ])
    _write_table(
        sheet, stem_headers, stem_rows,
        note=("GENERATED from config/stems.json. bunch_default_count normalizes bunch quotes to per-stem "
              "when a quote omits its own count — overridable per quote row."),
    )

    # Tier Recipes
    sheet = workbook.create_sheet(TAB_TIER_RECIPES)
    recipe_rows = []
    for tier in recipes["tiers"]:
        for item in tier["recipe"]:
            recipe_rows.append([
                tier["tier_id"], tier["name"], tier["retail_price_usd"], tier["margin_target"],
                item["stem_id"], item["count"], item["grade"], tier["placeholder"], tier.get("notes"),
            ])
    _write_table(
        sheet,
        ["tier_id", "tier_name", "retail_price_usd", "margin_target", "stem_id", "count",
         "grade", "placeholder", "notes"],
        recipe_rows,
        note=("WARNING: all tiers are PLACEHOLDER compositions — real recipes live in the website repo's "
              "products.json. Reconcile before trusting absolute dollar flags. GENERATED from config/tier-recipes.json."),
    )

    # Seasonal Calendar
    sheet = workbook.create_sheet(TAB_SEASONAL)
    window_rows = []
    for window in calendar["windows"]:
        overrides = ", ".join(f"{k}={v}" for k, v in window["stem_multipliers"].items())
        window_rows.append([
            window["id"], window["name"], window["start"], window["end"], window["peak_date"],
            window["is_holiday"], window["default_multiplier"], overrides, window.get("notes"),
        ])
    _write_table(
        sheet,
        ["window_id", "name", "start (MM-DD)", "end (MM-DD)", "peak_date", "is_holiday",
         "default_multiplier", "stem_multiplier_overrides", "notes"],
        window_rows,
        note=(f"GENERATED from config/seasonal-calendar.json. Vendor holiday cutoffs surface in the digest "
              f"{calendar['holiday_cutoff_lead_days']} days before each holiday peak."),
    )

    # Comparison (populated by the weekly run — WS5)
    sheet = workbook.create_sheet(TAB_COMPARISON)
    _write_table(
        sheet,
        ["stem_id", "grade", "cheapest_vendor", "price_per_stem", "quote_date", "quote_age_days",
         "runner_up_vendor", "runner_up_price", "spread_pct", "min_order_usd", "delivery",
         "payment_terms", "standing_order_requirement", "notes"],
        [],
        note=("GENERATED — populated by the weekly run once 2+ vendors have fresh quotes for a stem at "
              f"comparable grade. Margin thresholds: watch <{thresholds['margin_watch_below']:.0%}, "
              f"alert <{thresholds['margin_alert_below']:.0%}."),
    )

    # Digest Archive (weekly run appends)
    sheet = workbook.create_sheet(TAB_DIGEST)
    _write_table(
        sheet,
        ["digest_date", "headline", "moves_flagged", "tiers_affected", "cheapest_vendor_changes",
         "custom_quote_reprice_needed", "digest_link_or_text"],
        [],
        note="GENERATED — one row per weekly digest; full digest markdown is committed to reports/ in the repo.",
    )

    workbook.save(output_path)
    return output_path


# --- Workbook parsing (downloaded copy → rows) ---------------------------------

def _cell_to_text(value) -> str:
    if value is None:
        return ""
    if isinstance(value, datetime):
        return value.date().isoformat()
    if isinstance(value, date):
        return value.isoformat()
    return str(value).strip()


def _sheet_rows_as_dicts(sheet, headers: list[str], header_row: int) -> list[dict[str, str]]:
    rows = []
    for raw in sheet.iter_rows(min_row=header_row + 1, values_only=True):
        values = [_cell_to_text(value) for value in raw[: len(headers)]]
        if not any(values):
            continue
        rows.append(dict(zip(headers, values + [""] * (len(headers) - len(values)))))
    return rows


def parse_quick_entry_tab(
    workbook_path: Path,
    stems_config: dict | None = None,
    config_dir: Path = CONFIG_DIR,
) -> list[PriceLogRow]:
    # Quick Entry layout: row 1 note, row 2 headers, data from row 3.
    stems_config = stems_config or load_stems(config_dir)
    workbook = load_workbook(workbook_path, data_only=True)
    sheet = workbook[TAB_QUICK_ENTRY]
    parsed: list[PriceLogRow] = []
    for entry in _sheet_rows_as_dicts(sheet, QUICK_ENTRY_COLUMNS, header_row=2):
        if not entry.get("vendor_id") or not entry.get("stem_id"):
            continue
        base = dict(entry)
        base.setdefault("currency", "USD")
        row_dict = {**base, "id": "", "price_per_stem": "", "entered_at": "", "status": "confirmed"}
        row = PriceLogRow.from_csv_row(row_dict)
        row.price_per_stem = normalize_price_per_stem(
            row.quoted_price, row.quote_unit, row.units_per_quote_unit,
            stem_id=row.stem_id, stems_config=stems_config,
        )
        if row.quote_unit == "bunch" and row.units_per_quote_unit is None:
            # Record which default made the math so the log row is self-explaining.
            stem = next(s for s in stems_config["stems"] if s["id"] == row.stem_id)
            row.units_per_quote_unit = stem["units"]["bunch_default_count"]
            default_note = f"units_per_quote_unit defaulted to {row.units_per_quote_unit} (stems.json)"
            row.notes = f"{row.notes}; {default_note}" if row.notes else default_note
        parsed.append(row)
    return parsed


def parse_proposals_tab(workbook_path: Path) -> list[ProposalRow]:
    # Proposals layout: row 1 note, row 2 headers, data from row 3.
    workbook = load_workbook(workbook_path, data_only=True)
    sheet = workbook[TAB_PROPOSALS]
    proposals = []
    for entry in _sheet_rows_as_dicts(sheet, PROPOSAL_COLUMNS, header_row=2):
        if not entry.get("vendor_id") or not entry.get("stem_id"):
            continue
        proposals.append(ProposalRow.from_csv_row(entry))
    return proposals


# --- Merge ----------------------------------------------------------------------

def merge_rows_into_price_log(
    new_rows: list[PriceLogRow],
    csv_path: Path = DATA_DIR / "price-log.csv",
    config_dir: Path = CONFIG_DIR,
    entered_at: str | None = None,
) -> tuple[list[PriceLogRow], list[PriceLogRow]]:
    # Sheet rows → canonical CSV. Dedupe on (vendor_id, stem_id, date,
    # price_per_stem) so re-processing a downloaded workbook is idempotent.
    # Returns (added, skipped_duplicates).
    vendors_config = load_vendors(config_dir)
    stems_config = load_stems(config_dir)
    existing = read_price_log(csv_path)
    seen = {row.dedupe_key() for row in existing}
    entered_at = entered_at or datetime.now().astimezone().isoformat(timespec="seconds")

    added: list[PriceLogRow] = []
    skipped: list[PriceLogRow] = []
    sequence = len(existing)
    for row in new_rows:
        key = row.dedupe_key()
        if key in seen:
            skipped.append(row)
            continue
        sequence += 1
        if not row.id:
            row.id = f"pl-{row.date.replace('-', '')}-{sequence:05d}"
        if not row.entered_at:
            row.entered_at = entered_at
        row.validate(vendors_config=vendors_config, stems_config=stems_config)
        seen.add(key)
        existing.append(row)
        added.append(row)

    if added:
        write_price_log(existing, csv_path)
    return added, skipped
